controller_list:
  - name: fake_manipulator_i5_controller
    joints:
      - axis_x_joint
      - axis_y_joint
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint